### ISSUE TITLE
The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"exception":null,"success":false,"message":"Build failure"}']

### ISSUE THREAD

**Issue by gu3sss** [jmnarloch/gocd-sbt-plugin#2]
Getting the below error when running a SBT build pipeline in GoCD installed on Windows 10

2019-04-02 15:41:10,853 ERROR [scheduler-1] Builder:116 - Interaction with plugin with id 'sbt.task.plugin' implementing 'task' extension failed while requesting for 'execute'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"exception":null,"success":false,"message":"Build failure"}']
java.lang.RuntimeException: Interaction with plugin with id 'sbt.task.plugin' implementing 'task' extension failed while requesting for 'execute'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"exception":null,"success":false,"message":"Build failure"}']
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:57)
	at com.thoughtworks.go.plugin.access.pluggabletask.JsonBasedTaskExecutor.execute(JsonBasedTaskExecutor.java:42)
	at com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder.executeTask(PluggableTaskBuilder.java:89)
	at com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder.lambda$build$0(PluggableTaskBuilder.java:68)
	at com.thoughtworks.go.plugin.access.pluggabletask.TaskExtension.execute(TaskExtension.java:59)
	at com.thoughtworks.go.domain.builder.pluggableTask.PluggableTaskBuilder.build(PluggableTaskBuilder.java:68)
	at com.thoughtworks.go.remote.work.Builders.build(Builders.java:74)
	at com.thoughtworks.go.remote.work.BuildWork.execute(BuildWork.java:209)
	at com.thoughtworks.go.remote.work.BuildWork.buildJob(BuildWork.java:181)
	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:129)
	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:79)
	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:54)
	at com.thoughtworks.go.agent.AgentHTTPClientController.retrieveWork(AgentHTTPClientController.java:144)
	at com.thoughtworks.go.agent.AgentHTTPClientController.work(AgentHTTPClientController.java:116)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:85)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"exception":null,"success":false,"message":"Build failure"}'
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:55)
	... 26 common frames omitted

**Comment by gu3sss** [comment]
FYI, both GoCD Server and agent runs on same machine

**Comment by japzio** [comment]
this might be related to an empty config file or all contents are commented? we've encountered this on an yaml with all the lines are commented.
